#!/bin/bash

set -e

INPUT=time-mach
TO_BOX=to-box
PREFIX=time-mach

for fn in $(find $INPUT -type d -and -depth 1); do
	bn=$(basename $fn)
	dest="$TO_BOX/${PREFIX}-${bn}.tar.xz"
	if [ -f $dest ]; then
		echo "$dest exists. skipping."
	else
		echo "$fn => $dest"
		alert "tar cfJ $dest $fn"
	fi
done

